package com.anticheat.core.db

import com.anticheat.core.util.CoreLog
import java.security.MessageDigest

/**
 * 一次 schema 变更。
 *
 * <p>[checksum] 参与记录：迁移一旦执行过就不应再改。改了下一次启动会被检测出来并告警，
 * 而不是"静默地只在新库上生效"——那种前后不一致最终会表现为
 * "老服查询报列不存在，新服一切正常"，是最难查的一类问题。</p>
 */
class Migration(
    val version: Int,
    val name: String,
    val statements: List<String>
) {
    val checksum: String = sha1(name + "\n" + statements.joinToString("\n"))

    private fun sha1(text: String): String {
        val digest = MessageDigest.getInstance("SHA-1").digest(text.toByteArray(Charsets.UTF_8))
        val out = StringBuilder(digest.size * 2)
        for (byte in digest) {
            out.append(Character.forDigit((byte.toInt() shr 4) and 0xF, 16))
            out.append(Character.forDigit(byte.toInt() and 0xF, 16))
        }
        return out.toString()
    }
}

/**
 * 全部迁移，按版本号顺序执行。
 *
 * <h3>一套 DDL 同时给 H2 与 PostgreSQL</h3>
 * 见 [Sql] 的说明：时间用 `BIGINT`、IP/CIDR 用字符串、JSON 用字符串、
 * 自增用 `GENERATED BY DEFAULT AS IDENTITY`、"同时只允许一条生效"用可空唯一键。
 * 因此这里**没有任何方言分支**——如果将来某个语句只能在一个后端上跑，
 * 那说明写法退回了方言，应该改写法而不是加分支。
 *
 * <h3>为什么自建迁移器</h3>
 * 只需要三件事：有序、幂等、记录版本。为它引 Flyway/Liquibase 会多一份依赖，
 * 而本项目的 shade 规则里"谁提供同名类"已经出过两次线上事故。
 */
object Migrations {

    val ALL: List<Migration> by lazy { listOf(v001Basics(), v002RulesAndStats()) }

    @JvmStatic
    fun latestVersion(): Int = ALL.maxOfOrNull { it.version } ?: 0

    /**
     * V001：持久化主干——玩家档案 / 用户名历史 / IP 记录 / 封禁 / 违规 / 审计。
     */
    private fun v001Basics(): Migration = Migration(
        1, "basics", listOf(
            """
            CREATE TABLE IF NOT EXISTS player_profile (
                uuid             UUID PRIMARY KEY,
                name             VARCHAR(16) NOT NULL,
                first_seen       BIGINT      NOT NULL,
                last_seen        BIGINT      NOT NULL,
                last_ip          VARCHAR(64),
                sessions         INTEGER     NOT NULL DEFAULT 0,
                playtime_secs    BIGINT      NOT NULL DEFAULT 0,
                risk_score       REAL        NOT NULL DEFAULT 0,
                risk_updated     BIGINT,
                total_violations INTEGER     NOT NULL DEFAULT 0,
                violations_24h   INTEGER     NOT NULL DEFAULT 0,
                violations_7d    INTEGER     NOT NULL DEFAULT 0,
                profile_blob     VARCHAR,
                profile_updated  BIGINT
            )
            """.trimIndent(),
            "CREATE INDEX IF NOT EXISTS idx_profile_name ON player_profile (name)",
            "CREATE INDEX IF NOT EXISTS idx_profile_last_seen ON player_profile (last_seen)",
            "CREATE INDEX IF NOT EXISTS idx_profile_risk ON player_profile (risk_score)",
            // 用户名历史单独一张表：可以按旧名反查账号（"这个号以前叫什么"、
            // "这个名字被哪些 uuid 用过"），这是原来那种"把历史塞进一个字符串"做不到的。
            """
            CREATE TABLE IF NOT EXISTS player_name (
                uuid       UUID        NOT NULL,
                name       VARCHAR(16) NOT NULL,
                first_seen BIGINT      NOT NULL,
                last_seen  BIGINT      NOT NULL,
                uses       INTEGER     NOT NULL DEFAULT 1,
                PRIMARY KEY (uuid, name)
            )
            """.trimIndent(),
            "CREATE INDEX IF NOT EXISTS idx_player_name_name ON player_name (name)",
            // IP 与网段都存字符串：网段匹配在 IpIntel 里做（纯逻辑、已单测），
            // 这样 H2 与 PostgreSQL 跑的是同一套 SQL，不需要 INET/CIDR 类型与 >>= 操作符。
            """
            CREATE TABLE IF NOT EXISTS player_ip (
                uuid        UUID        NOT NULL,
                ip          VARCHAR(64) NOT NULL,
                ip_family   SMALLINT    NOT NULL,
                cidr        VARCHAR(64) NOT NULL,
                asn         INTEGER,
                asn_org     VARCHAR(128),
                country     VARCHAR(8),
                first_seen  BIGINT      NOT NULL,
                last_seen   BIGINT      NOT NULL,
                login_count INTEGER     NOT NULL DEFAULT 1,
                PRIMARY KEY (uuid, ip)
            )
            """.trimIndent(),
            "CREATE INDEX IF NOT EXISTS idx_player_ip_ip ON player_ip (ip)",
            "CREATE INDEX IF NOT EXISTS idx_player_ip_cidr ON player_ip (cidr)",
            "CREATE INDEX IF NOT EXISTS idx_player_ip_last_seen ON player_ip (last_seen)",
            // 封禁：kind=uuid/ip/cidr，scope=temp/perm，status=active/expired/revoked。
            // active_key 只在生效时非空（'uuid:<id>' / 'ip:<x>' / 'cidr:<x>'），
            // 靠它的唯一约束保证"同一目标同时只有一条生效封禁"——两个引擎对
            // "唯一索引里可以有多少个 NULL" 的语义一致（可以任意多个），
            // 而 PostgreSQL 的部分唯一索引 H2 没有。
            """
            CREATE TABLE IF NOT EXISTS ban (
                id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                kind          VARCHAR(8)   NOT NULL,
                target        VARCHAR(64)  NOT NULL,
                name          VARCHAR(16),
                uuid          UUID,
                scope         VARCHAR(8)   NOT NULL,
                reason        VARCHAR(255) NOT NULL,
                operator      VARCHAR(32)  NOT NULL,
                issued_at     BIGINT       NOT NULL,
                expires_at    BIGINT,
                status        VARCHAR(8)   NOT NULL,
                revoked_by    VARCHAR(32),
                revoked_at    BIGINT,
                revoke_reason VARCHAR(255),
                server_name   VARCHAR(32),
                violation_id  BIGINT,
                active_key    VARCHAR(96),
                CONSTRAINT uq_ban_active UNIQUE (active_key)
            )
            """.trimIndent(),
            "CREATE INDEX IF NOT EXISTS idx_ban_uuid ON ban (uuid)",
            "CREATE INDEX IF NOT EXISTS idx_ban_target ON ban (target)",
            "CREATE INDEX IF NOT EXISTS idx_ban_status_expires ON ban (status, expires_at)",
            "CREATE INDEX IF NOT EXISTS idx_ban_issued ON ban (issued_at)",
            """
            CREATE TABLE IF NOT EXISTS violation (
                id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                uuid           UUID        NOT NULL,
                name           VARCHAR(16) NOT NULL,
                check_name     VARCHAR(32) NOT NULL,
                check_group    VARCHAR(24),
                vl             REAL        NOT NULL,
                vl_delta       REAL        NOT NULL,
                severity       SMALLINT    NOT NULL DEFAULT 1,
                created_at     BIGINT      NOT NULL,
                day_bucket     BIGINT      NOT NULL,
                server_name    VARCHAR(32),
                world          VARCHAR(64),
                x              DOUBLE PRECISION,
                y              DOUBLE PRECISION,
                z              DOUBLE PRECISION,
                ping           INTEGER,
                tps            REAL,
                client_version VARCHAR(24),
                packet_type    VARCHAR(48),
                detail         VARCHAR,
                experimental   BOOLEAN     NOT NULL DEFAULT FALSE,
                punished       BOOLEAN     NOT NULL DEFAULT FALSE,
                punish_action  VARCHAR(24)
            )
            """.trimIndent(),
            "CREATE INDEX IF NOT EXISTS idx_viol_time ON violation (created_at)",
            "CREATE INDEX IF NOT EXISTS idx_viol_uuid_time ON violation (uuid, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_viol_check_time ON violation (check_name, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_viol_day ON violation (day_bucket, check_name)",
            // 审计沿用旧口径：时间戳是 epoch 毫秒。列名用 ts 而不是 timestamp：
            // TIMESTAMP 在 H2 里是数据类型关键字，当列名有兼容风险。
            """
            CREATE TABLE IF NOT EXISTS audit_log (
                id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts            BIGINT NOT NULL,
                operator      VARCHAR(64),
                operator_role INTEGER,
                type          VARCHAR(64),
                target        VARCHAR(128),
                ip            VARCHAR(64),
                result        VARCHAR(16),
                detail        VARCHAR
            )
            """.trimIndent(),
            "CREATE INDEX IF NOT EXISTS idx_audit_ts ON audit_log (ts)",
            "CREATE INDEX IF NOT EXISTS idx_audit_operator ON audit_log (operator)",
            "CREATE INDEX IF NOT EXISTS idx_audit_type ON audit_log (type)"
        )
    )

    /**
     * V002：规则与统计——检测阈值 / 惩罚阶梯 / 白名单 / 检查命中率 / 风险画像。
     */
    private fun v002RulesAndStats(): Migration = Migration(
        2, "rules_and_stats", listOf(
            """
            CREATE TABLE IF NOT EXISTS check_rule (
                check_name   VARCHAR(32) PRIMARY KEY,
                enabled      BOOLEAN     NOT NULL DEFAULT TRUE,
                decay        REAL,
                setback      REAL,
                experimental BOOLEAN     NOT NULL DEFAULT FALSE,
                description  VARCHAR(255),
                thresholds   VARCHAR,
                updated_at   BIGINT      NOT NULL,
                updated_by   VARCHAR(32)
            )
            """.trimIndent(),
            """
            CREATE TABLE IF NOT EXISTS punishment_ladder (
                step       SMALLINT    PRIMARY KEY,
                min_vl     REAL        NOT NULL,
                action     VARCHAR(24) NOT NULL,
                duration   VARCHAR(24),
                reason     VARCHAR(255),
                updated_at BIGINT      NOT NULL
            )
            """.trimIndent(),
            """
            CREATE TABLE IF NOT EXISTS whitelist_entry (
                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                uuid       UUID,
                name       VARCHAR(16),
                reason     VARCHAR(255),
                added_by   VARCHAR(32),
                added_at   BIGINT NOT NULL,
                expires_at BIGINT,
                active_key VARCHAR(48),
                CONSTRAINT uq_whitelist_active UNIQUE (active_key)
            )
            """.trimIndent(),
            "CREATE INDEX IF NOT EXISTS idx_whitelist_name ON whitelist_entry (name)",
            """
            CREATE TABLE IF NOT EXISTS check_stat (
                bucket      BIGINT      NOT NULL,
                check_name  VARCHAR(32) NOT NULL,
                evaluations BIGINT      NOT NULL DEFAULT 0,
                flags       BIGINT      NOT NULL DEFAULT 0,
                vl_sum      REAL        NOT NULL DEFAULT 0,
                players     INTEGER     NOT NULL DEFAULT 0,
                PRIMARY KEY (bucket, check_name)
            )
            """.trimIndent(),
            """
            CREATE TABLE IF NOT EXISTS risk_snapshot (
                id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                uuid         UUID     NOT NULL,
                score        REAL     NOT NULL,
                violations   INTEGER  NOT NULL,
                window_hours SMALLINT NOT NULL,
                computed_at  BIGINT   NOT NULL
            )
            """.trimIndent(),
            "CREATE INDEX IF NOT EXISTS idx_risk_snapshot_uuid ON risk_snapshot (uuid, computed_at)",
            // ---- 视图：聚合口径只在视图里定义一次，看板/命令/排障共用 ----
            // 先 DROP 再 CREATE：`CREATE OR REPLACE VIEW` 的列兼容要求两个引擎不一致
            "DROP VIEW IF EXISTS v_violation_trend",
            "CREATE VIEW v_violation_trend AS " +
                // 别名刻意叫 day_bucket 而不是 day：DAY 是 SQL 保留字，
                // H2 会直接拒绝（PG 能过但属于靠运气），而两个后端必须跑同一套 DDL
                "SELECT day_bucket, check_name, count(*) AS violations, " +
                "count(DISTINCT uuid) AS players, avg(vl_delta) AS avg_vl_delta, max(vl) AS max_vl " +
                "FROM violation GROUP BY day_bucket, check_name",
            "DROP VIEW IF EXISTS v_check_hit_rate",
            "CREATE VIEW v_check_hit_rate AS " +
                "SELECT check_name, sum(evaluations) AS evaluations, sum(flags) AS flags, " +
                "CASE WHEN sum(evaluations) > 0 THEN sum(flags) * 1.0 / sum(evaluations) ELSE NULL END AS hit_rate, " +
                "max(bucket) AS last_bucket FROM check_stat GROUP BY check_name",
            "DROP VIEW IF EXISTS v_player_risk",
            // 风险画像只读档案表里**已算好**的列：近 24h/7d 违规数由
            // RiskRefresh 任务写入（每 risk-refresh-minutes 一次）。
            // 这样做的原因：视图里算"最近 24 小时"需要 now()/interval 这类方言函数，
            // 而把它们换成"写入时算好"既省了每次查询的全表扫描，也让两个引擎完全一致。
            "CREATE VIEW v_player_risk AS " +
                "SELECT uuid, name, risk_score, total_violations, violations_24h, violations_7d, last_seen, last_ip " +
                "FROM player_profile"
        )
    )
}

/** 迁移执行结果（用于启动日志与测试断言）。 */
class MigrationResult(
    val applied: List<Int>,
    val skipped: Int,
    val checksumMismatches: List<Int>,
    val latestVersion: Int
) {
    fun describe(): String {
        val base = "schema v" + latestVersion +
            "（本次执行 " + applied.size + " 个迁移，跳过 " + skipped + " 个已执行版本）"
        if (checksumMismatches.isEmpty()) return base
        return base + " ⚠ 校验和不一致（迁移被改过）: " + checksumMismatches
    }
}

/**
 * 迁移执行器。
 *
 * <p>每个迁移在**独立事务**里执行：中途失败时该版本整体回滚，
 * 不会留下"建了一半的表"——那种状态下重跑 `CREATE TABLE IF NOT EXISTS` 恰好能建完，
 * 但索引与视图会缺，而且要人工判断缺了什么。</p>
 */
class Migrator(private val pool: JdbcPool) {

    fun migrate(): MigrationResult {
        ensureVersionTable()

        val applied = ArrayList<Int>()
        val mismatches = ArrayList<Int>()
        var skipped = 0

        val known = readApplied()
        for (migration in Migrations.ALL) {
            val recorded = known[migration.version]
            if (recorded != null) {
                if (recorded != migration.checksum) {
                    mismatches.add(migration.version)
                    CoreLog.warn(
                        "数据库迁移 v" + migration.version + " 的校验和与记录不一致：" +
                            "该版本已被修改但不会重跑（库结构可能与代码不再一致，建议手工核对）"
                    )
                }
                skipped++
                continue
            }
            pool.withTransaction { connection ->
                connection.createStatement().use { statement ->
                    for (sql in migration.statements) {
                        statement.execute(sql)
                    }
                }
                true
            }
            pool.withTransaction { connection ->
                connection.prepareStatement(
                    "INSERT INTO schema_version (version, name, checksum, applied_at) VALUES (?, ?, ?, ?)"
                ).use { insert ->
                    insert.setInt(1, migration.version)
                    insert.setString(2, migration.name)
                    insert.setString(3, migration.checksum)
                    insert.setLong(4, System.currentTimeMillis())
                    insert.executeUpdate()
                }
                true
            }
            applied.add(migration.version)
        }

        return MigrationResult(applied, skipped, mismatches, Migrations.latestVersion())
    }

    private fun ensureVersionTable() {
        pool.withConnection { connection ->
            connection.createStatement().use { statement ->
                statement.execute(
                    """
                    CREATE TABLE IF NOT EXISTS schema_version (
                        version    INTEGER     PRIMARY KEY,
                        name       VARCHAR(64) NOT NULL,
                        checksum   VARCHAR(64) NOT NULL,
                        applied_at BIGINT      NOT NULL
                    )
                    """.trimIndent()
                )
            }
            true
        }
    }

    private fun readApplied(): Map<Int, String> {
        val result = HashMap<Int, String>()
        pool.withConnection { connection ->
            connection.createStatement().use { statement ->
                statement.executeQuery("SELECT version, checksum FROM schema_version").use { rows ->
                    while (rows.next()) {
                        result[rows.getInt("version")] = rows.getString("checksum")
                    }
                }
            }
            true
        }
        return result
    }
}
