package com.anticheat.core.db

import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.ResultSet
import java.sql.SQLException
import java.sql.Statement
import java.sql.Types
import java.util.UUID

/**
 * SQL 边界的公共工具。
 *
 * <h3>为什么把 SQL 收敛到"可移植子集"</h3>
 * 本插件要同时支持 **H2（嵌入式、默认、保底）** 与 **PostgreSQL（外置、可选）**，
 * 而两者的方言差异很大：`INET`/`CIDR`、`JSONB`、数组、`RETURNING`、部分唯一索引、
 * `ON CONFLICT`、`interval`、`date_trunc`、`extract(epoch ...)` 这些在 H2 上都没有。
 * 如果按方言写两套代码，就等于两套 schema、两套查询、两套测试，而且
 * "某个后端少改了一处"这类漂移在单后端测试下根本发现不了。
 *
 * <p>因此统一约定（这是整个 db 包的纪律）：</p>
 * - **时间一律 `BIGINT`（epoch 毫秒）**：插件内部的时间语义本来就是毫秒，
 *   取消 `timestamptz`/`now()`/`interval` 之后，所有"最近 24 小时"都是绑定一个
 *   由 Kotlin 算好的毫秒阈值——顺带还让查询用得上索引；
 * - **IP / CIDR 一律 `VARCHAR`**，网段匹配在 [IpIntel] 里做（纯逻辑、已单测）；
 * - **JSON 一律 `VARCHAR`**（[RuleRepository] 用 Gson 读写）；
 * - **自增用 `GENERATED BY DEFAULT AS IDENTITY`**（PG 10+ 与 H2 2.x 都支持）；
 * - **"同时只允许一条生效"用可空唯一键**（`active_key`），而不是 PostgreSQL 的
 *   部分唯一索引——唯一索引允许多个 NULL，这个语义两个引擎一致；
 * - **不写 `ON CONFLICT` / `RETURNING`**：前者 H2 支持不完整，后者是 PG 扩展；
 *   改用下面的 [upsert] 与 [insertReturningId]。
 */
object Sql {

    /** 读一个 BIGINT 时间列（缺省 0）。 */
    @JvmStatic
    fun millis(rows: ResultSet, column: String): Long = rows.getLong(column)

    /** 读一个可空 BIGINT 时间列。 */
    @JvmStatic
    fun millisOrNull(rows: ResultSet, column: String): Long? {
        val value = rows.getLong(column)
        return if (rows.wasNull()) null else value
    }

    /** 读 UUID 列。 */
    @JvmStatic
    fun uuid(rows: ResultSet, column: String): UUID? = uuidOrNull(rows.getString(column))

    @JvmStatic
    fun uuidOrNull(text: String?): UUID? {
        if (text.isNullOrEmpty()) return null
        return try {
            UUID.fromString(text)
        } catch (t: Throwable) {
            null
        }
    }

    @JvmStatic
    fun intOrNull(rows: ResultSet, column: String): Int? {
        val value = rows.getInt(column)
        return if (rows.wasNull()) null else value
    }

    @JvmStatic
    fun longOrNull(rows: ResultSet, column: String): Long? {
        val value = rows.getLong(column)
        return if (rows.wasNull()) null else value
    }

    @JvmStatic
    fun doubleOrNull(rows: ResultSet, column: String): Double? {
        val value = rows.getDouble(column)
        return if (rows.wasNull()) null else value
    }

    @JvmStatic
    fun floatOrNull(rows: ResultSet, column: String): Float? {
        val value = rows.getFloat(column)
        return if (rows.wasNull()) null else value
    }

    /** 写字符串：空串按 NULL 处理（空串会污染唯一键与 LIKE 查询）。 */
    @JvmStatic
    fun setString(statement: PreparedStatement, index: Int, value: String?) {
        if (value == null || value.isEmpty()) {
            statement.setNull(index, Types.VARCHAR)
        } else {
            statement.setString(index, value)
        }
    }

    @JvmStatic
    fun setInt(statement: PreparedStatement, index: Int, value: Int?) {
        if (value == null) statement.setNull(index, Types.INTEGER) else statement.setInt(index, value)
    }

    @JvmStatic
    fun setLong(statement: PreparedStatement, index: Int, value: Long?) {
        if (value == null) statement.setNull(index, Types.BIGINT) else statement.setLong(index, value)
    }

    @JvmStatic
    fun setDouble(statement: PreparedStatement, index: Int, value: Double?) {
        if (value == null) statement.setNull(index, Types.DOUBLE) else statement.setDouble(index, value)
    }

    @JvmStatic
    fun setFloat(statement: PreparedStatement, index: Int, value: Float?) {
        if (value == null) statement.setNull(index, Types.REAL) else statement.setFloat(index, value)
    }

    /**
     * 插入并取回自增主键。
     *
     * <p>用 JDBC 标准的 `RETURN_GENERATED_KEYS` 而不是 PostgreSQL 的 `RETURNING`：
     * 后者 H2 不支持，写两套就等于把"取主键"这件事分叉成两份实现。</p>
     *
     * @return 新 id；驱动没返回主键时返回 -1（调用方不应把 -1 当成"插入失败"，
     *   因为插入本身已经成功）
     */
    @JvmStatic
    fun insertReturningId(connection: Connection, sql: String, binder: (PreparedStatement) -> Unit): Long {
        connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS).use { statement ->
            binder(statement)
            statement.executeUpdate()
            statement.generatedKeys.use { keys ->
                return if (keys.next()) keys.getLong(1) else -1L
            }
        }
    }

    /**
     * 可移植的 upsert：先 UPDATE，没改到行再 INSERT，撞唯一键则重试一次 UPDATE。
     *
     * <p>为什么不用 `MERGE`（H2）或 `ON CONFLICT`（PG）：两者语法不同且 H2 的
     * `ON CONFLICT ... DO UPDATE` 支持不完整，写两套会让"新增一个 upsert"
     * 变成"要记得改两个地方"。</p>
     *
     * <p>并发下的正确性：两个线程可能同时判定"行不存在"，然后一起 INSERT，
     * 其中一个会撞唯一键。撞键恰恰说明行已被另一个线程建好，因此**重试 UPDATE**
     * 就是正确答案——而不是把异常抛给调用方（那会变成"偶发写入失败"）。</p>
     *
     * <p>调用方必须在事务里调用它（[JdbcPool.withTransaction]），
     * 否则"UPDATE 没生效 + INSERT 失败"之间会留下不可见的中间态。</p>
     *
     * @return true = 至少写成功了一次
     */
    @JvmStatic
    fun upsert(
        connection: Connection,
        updateSql: String,
        bindUpdate: (PreparedStatement) -> Unit,
        insertSql: String,
        bindInsert: (PreparedStatement) -> Unit
    ): Boolean {
        connection.prepareStatement(updateSql).use { statement ->
            bindUpdate(statement)
            if (statement.executeUpdate() > 0) return true
        }
        try {
            connection.prepareStatement(insertSql).use { statement ->
                bindInsert(statement)
                statement.executeUpdate()
            }
            return true
        } catch (conflict: SQLException) {
            connection.prepareStatement(updateSql).use { statement ->
                bindUpdate(statement)
                return statement.executeUpdate() > 0
            }
        }
    }

    /** 执行一条无参数语句（DDL / 简单 DELETE）。 */
    @JvmStatic
    fun execute(connection: Connection, sql: String) {
        connection.createStatement().use { it.execute(sql) }
    }

    /**
     * epoch 毫秒 → 所在"天"的起点（UTC）。
     *
     * <p>趋势统计按天分组，而 `date_trunc` 是方言相关的（H2 没有 PG 的
     * `date_trunc` 语义），所以**分组键在写入时算好存成一个 BIGINT 列**
     * （`day_bucket`）。这样聚合就是普通的 `GROUP BY` + 索引，
     * 比每次查询现场截断时间还快。</p>
     */
    @JvmStatic
    fun dayBucket(millis: Long): Long = millis - Math.floorMod(millis, 86_400_000L)
}
